-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 12:09:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` DEFAULT CHARACTER SET utf8 ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `escuela`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `apellido` VARCHAR(75) NOT NULL,
  `profesion` VARCHAR(3) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  `dui` VARCHAR(10) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`grado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grado` VARCHAR(60) NOT NULL,
  `seccion` VARCHAR(2) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `profesor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grado_profesor_idx` (`profesor_id` ASC),
  CONSTRAINT `fk_grado_profesor`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `escuela`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`estudiante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  `apellido` VARCHAR(75) NOT NULL,
  `dui` VARCHAR(10) NULL,
  `genero` VARCHAR(1) NOT NULL,
  `carnet` VARCHAR(9) NOT NULL,
  `grado_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiante_grado1_idx` (`grado_id` ASC),
  CONSTRAINT `fk_estudiante_grado1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `escuela`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
